# Generated by Django 5.0.2 on 2024-03-27 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=100)),
                ('releaseDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('msgID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=20)),
                ('msg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('actors', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=20)),
                ('release_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('trailer_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayofweek', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20)),
                ('date', models.DateField()),
                ('slot1', models.TimeField()),
                ('slot2', models.TimeField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
