# Generated by Django 5.0.2 on 2024-04-10 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_carddata_customermessage_movie_showtime_delete_demo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardData',
        ),
    ]
