# Generated by Django 5.0.2 on 2024-04-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_delete_carddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='slot1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='slot2',
            field=models.CharField(default='Break', max_length=100),
        ),
    ]
