# Generated by Django 5.0.2 on 2024-04-10 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_showtime_slot1_alter_showtime_slot2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='movie',
        ),
        migrations.AlterField(
            model_name='showtime',
            name='slot1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot1', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='slot2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot2', to='movies.movie'),
        ),
    ]
