# Generated by Django 5.0.2 on 2024-04-10 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_showtime_movie_alter_showtime_slot1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='slot1',
            field=models.ForeignKey(limit_choices_to={'status': 'Now Playing'}, on_delete=django.db.models.deletion.CASCADE, related_name='slot1', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='slot2',
            field=models.ForeignKey(limit_choices_to={'status': 'Now Playing'}, on_delete=django.db.models.deletion.CASCADE, related_name='slot2', to='movies.movie'),
        ),
    ]
