# Generated by Django 5.0.2 on 2024-04-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_showtime_slot1_alter_showtime_slot2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='dayofweek',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20),
        ),
    ]
