# Generated by Django 5.0.2 on 2024-04-10 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_showtime_dayofweek'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='showtime',
            unique_together={('dayofweek', 'date')},
        ),
    ]
