# Generated by Django 5.0.2 on 2024-04-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_movie_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.CharField(choices=[('Row 1 Seat 1', 'Row 1 Seat 1'), ('Row 1 Seat 2', 'Row 1 Seat 2'), ('Row 1 Seat 3', 'Row 1 Seat 3'), ('Row 1 Seat 4', 'Row 1 Seat 4'), ('Row 1 Seat 5', 'Row 1 Seat 5'), ('Row 1 Seat 6', 'Row 1 Seat 6'), ('Row 1 Seat 7', 'Row 1 Seat 7'), ('Row 1 Seat 8', 'Row 1 Seat 8'), ('Row 2 Seat 1', 'Row 2 Seat 1'), ('Row 2 Seat 2', 'Row 2 Seat 2'), ('Row 2 Seat 3', 'Row 2 Seat 3'), ('Row 2 Seat 4', 'Row 2 Seat 4'), ('Row 2 Seat 5', 'Row 2 Seat 5'), ('Row 2 Seat 6', 'Row 2 Seat 6'), ('Row 2 Seat 7', 'Row 2 Seat 7'), ('Row 2 Seat 8', 'Row 2 Seat 8'), ('Row 3 Seat 1', 'Row 3 Seat 1'), ('Row 3 Seat 2', 'Row 3 Seat 2'), ('Row 3 Seat 3', 'Row 3 Seat 3'), ('Row 3 Seat 4', 'Row 3 Seat 4'), ('Row 3 Seat 5', 'Row 3 Seat 5'), ('Row 3 Seat 6', 'Row 3 Seat 6'), ('Row 3 Seat 7', 'Row 3 Seat 7'), ('Row 3 Seat 8', 'Row 3 Seat 8'), ('Row 4 Seat 1', 'Row 4 Seat 1'), ('Row 4 Seat 2', 'Row 4 Seat 2'), ('Row 4 Seat 3', 'Row 4 Seat 3'), ('Row 4 Seat 4', 'Row 4 Seat 4'), ('Row 4 Seat 5', 'Row 4 Seat 5'), ('Row 4 Seat 6', 'Row 4 Seat 6'), ('Row 4 Seat 7', 'Row 4 Seat 7'), ('Row 4 Seat 8', 'Row 4 Seat 8'), ('Row 5 Seat 1', 'Row 5 Seat 1'), ('Row 5 Seat 2', 'Row 5 Seat 2'), ('Row 5 Seat 3', 'Row 5 Seat 3'), ('Row 5 Seat 4', 'Row 5 Seat 4'), ('Row 5 Seat 5', 'Row 5 Seat 5'), ('Row 5 Seat 6', 'Row 5 Seat 6'), ('Row 5 Seat 7', 'Row 5 Seat 7'), ('Row 5 Seat 8', 'Row 5 Seat 8')], default='Row 1 Seat 1', max_length=15)),
                ('booked', models.BooleanField(default=False)),
            ],
        ),
    ]
