# Generated by Django 5.0.2 on 2024-04-28 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_alter_booking_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='movie',
            new_name='movieName',
        ),
    ]
