# Generated by Django 5.0.2 on 2024-04-28 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_rename_movie_booking_moviename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='movieName',
        ),
        migrations.AddField(
            model_name='booking',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
    ]
