# Generated by Django 5.0.2 on 2024-04-29 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_remove_booking_moviename_booking_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowtimeMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('slotChoice', models.CharField(choices=[('Slot1', 'Slot 1'), ('Slot2', 'Slot 2')], default='slot not chosen', max_length=20)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='bookingTime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.showtimemapper'),
        ),
    ]
