# Generated by Django 5.0.2 on 2024-05-03 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_booking_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='seat',
            name='showtime_mapper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movies.showtimemapper'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('row', 'number', 'showtime_mapper')},
        ),
    ]
