# Generated by Django 5.0.2 on 2024-05-03 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_remove_booking_seats_alter_seat_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('seat', 'bookingTime')},
        ),
    ]
