# Generated by Django 5.0.2 on 2024-06-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0024_couponcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='discountAmount',
            field=models.IntegerField(blank=True, help_text='Enter the discount amount you are willing to provide', null=True),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='discountPercent',
            field=models.IntegerField(blank=True, help_text='Enter the percentage amount you are willing to provide', null=True),
        ),
    ]
