# Generated by Django 5.0.2 on 2024-04-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='wears',
            name='backLength',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wears',
            name='frontLength',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wears',
            name='productBody',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='wears',
            name='productImage',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='wears',
            name='productColor',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
