# Generated by Django 5.0.2 on 2024-04-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_featured_offer_wears_backlength_wears_frontlength_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wears',
            name='backLength',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wears',
            name='frontLength',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wears',
            name='productName',
            field=models.CharField(max_length=100),
        ),
    ]
