# Generated by Django 5.0.2 on 2024-04-21 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_wears_backlength_alter_wears_frontlength_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured',
            name='message',
            field=models.CharField(default='Featured', max_length=50),
        ),
        migrations.AddField(
            model_name='featured',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured', to='management.wears'),
        ),
        migrations.AddField(
            model_name='offer',
            name='Discount',
            field=models.CharField(default='Discounts', max_length=50),
        ),
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounted', to='management.wears'),
        ),
        migrations.AlterField(
            model_name='wears',
            name='productColor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
