# Generated by Django 5.0.2 on 2024-04-29 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_featured_message_featured_product_offer_discount_and_more'),
    ]

    operations = [
    ]
