# Generated by Django 5.0.2 on 2024-05-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='customer_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='customer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='customer_phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
