# Generated by Django 5.0.2 on 2024-05-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_shipping_session_key_alter_shipping_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(choices=[('SummerWear', 'Summerwear'), ('WinterWear', 'Winterwear'), ('Western', 'Western'), ('Cotton', 'Cotton')], max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='wears',
            old_name='category',
            new_name='summerOrWinter',
        ),
        migrations.AddField(
            model_name='wears',
            name='categories',
            field=models.ManyToManyField(to='management.category'),
        ),
    ]
