# Generated by Django 5.0.2 on 2024-05-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_category_rename_category_wears_summerorwinter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryName',
            field=models.CharField(choices=[('SummerWear', 'Summerwear'), ('WinterWear', 'Winterwear'), ('Western', 'Western'), ('Cotton', 'Cotton')], max_length=100, unique=True),
        ),
    ]
