# Generated by Django 5.0.2 on 2024-06-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_alter_category_categoryname'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='delivery_time_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='delivery_time_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
