# Generated by Django 5.0.2 on 2024-06-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_shipping_delivery_time_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='shippingStatus',
            field=models.CharField(blank=True, choices=[('preparing', 'Preparing'), ('packaging', 'Packaging'), ('shipping', 'Shipping')], default='preparing', max_length=20, null=True),
        ),
    ]
