# Generated by Django 5.0.2 on 2024-06-02 03:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_shipping_shippingstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='shippingStatus',
            field=models.CharField(blank=True, choices=[('Preparing', 'Preparing'), ('Packaging', 'Packaging'), ('Shipping', 'Shipping')], default='Preparing', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ShippedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivedDate', models.DateField(default=django.utils.timezone.now)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.shipping')),
            ],
        ),
    ]
