# Generated by Django 5.0.2 on 2024-06-02 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_alter_shipping_shippingstatus_shippeditems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippeditems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.shipping'),
        ),
    ]
