# Generated by Django 5.0.2 on 2024-06-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_couponcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippeditems',
            name='item',
        ),
        migrations.AddField(
            model_name='shippeditems',
            name='customerEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shippeditems',
            name='customerName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippeditems',
            name='customerPhone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippeditems',
            name='product',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shippeditems',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
