# Generated by Django 5.0.2 on 2024-06-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_shippeditems_session_key_shippeditems_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
