# Generated by Django 5.0.2 on 2024-07-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_userreview_session_key_alter_userreview_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wears',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='wears',
            name='summerOrWinter',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='wears',
            name='categories',
            field=models.CharField(choices=[('SummerWear', 'Summerwear'), ('WinterWear', 'Winterwear'), ('Western', 'Western'), ('Cotton', 'Cotton')], default='SummerWear', max_length=20),
        ),
    ]
